name: hateSpeech
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pandas=1.3.4
  - matplotlib=3.5.0
  - scikit-learn=1.0.1
  - wordcloud=1.8.1
  - gensim=4.1.2
  - spacy=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.1.0
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyterlab=3.2.4
  - pyLDAvis=3.3.1
  - pip=21.3.1
  - nltk
  - pip:
      - praw===7.5.0
      - emoji==1.6.1
